# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


