# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('counter_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(verbose_name='date probed')),
                ('tag', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_ip', models.CharField(max_length=25)),
                ('probing_frequency', models.PositiveIntegerField()),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('last_probed', models.DateTimeField(verbose_name='last probed')),
                ('last_status', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('error_msg', models.CharField(max_length=200)),
                ('last_failure', models.DateTimeField(verbose_name='last failed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Service'),
        ),
        migrations.AddField(
            model_name='counter',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Node'),
        ),
    ]
