# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20161215_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
