# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161215_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='last_failure',
            field=models.DateTimeField(blank=True),
        ),
    ]
